# Generated by Django 4.1.13 on 2024-07-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Email', models.TextField()),
                ('Phonenumber', models.IntegerField()),
                ('Dateofjoin', models.TextField()),
            ],
        ),
    ]
